version: '3.8'
services:
    app:
        container_name: travel_app
        build: .
        image: travelcom-app
        ports:
            - '8000:80'
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        depends_on:
            - travel_mysql
        networks:
            - travel_network
    travel_mysql:
        image: mysql:8.0
        container_name: travel_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vacaciones
            MYSQL_USER: travel_user
            MYSQL_PASSWORD: travel_password
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - travel_network
    travel_phpmyadmin:
        image: phpmyadmin:latest
        container_name: travel_phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: travel_mysql
            PMA_USER: travel_user
            PMA_PASSWORD: travel_password
        depends_on:
            - travel_mysql
        networks:
            - travel_network
networks:
    travel_network:
        driver: bridge
volumes:
    db_data:
